version: "3.3"
services:
  postgres:
    image: postgres:9.6
    container_name: dev_postgres_untilla
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=the_your_password
      - PGDATA=/tmp
